default_context:
  project_name: 'gt-planner-prototype'
  project_slug: 'gt-planner-prototype'
  domain_main: 'gt-planner.org'
  domain_staging: 'gt-planner-dev.org'
  docker_swarm_stack_name_main: 'gt-planner-docker-stack-main'
  docker_swarm_stack_name_staging: 'gt-planner-docker-stack-staging'
  secret_key: 'ca519689e7b9b4110572953646f946f8089e56ab3bc9c062748b232da25a64ee'
  first_superuser: 'su'
  first_superuser_password: 'ca519689e7b9b4110572953646f946f8089e56ab3bc9c062748b232da25a64ee'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.gt-planner.org", "https://gt-planner-dev.org", "https://gt-planner.org", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@gt-planner.org'
  postgres_password: 'ca519689e7b9b4110572953646f946f8089e56ab3bc9c062748b232da25a64ee'
  pgadmin_default_user: 'su'
  pgadmin_default_user_password: 'ca519689e7b9b4110572953646f946f8089e56ab3bc9c062748b232da25a64ee'
  traefik_constraint_tag: 'gt-planner.org'
  traefik_constraint_tag_staging: 'gt-planner-dev.org'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ca519689e7b9b4110572953646f946f8089e56ab3bc9c062748b232da25a64ee'
  sentry_dsn: ''
  docker_image_prefix: 'gt-planner/'
  docker_image_backend: 'gt-planner/backend'
  docker_image_celeryworker: 'gt-planner/celeryworker'
  docker_image_frontend: 'gt-planner/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
